### ISSUE TITLE
media.go error causes go get github.com/grokify/go-voicebase-v3@master to fail

### ISSUE THREAD

**Issue by timbunce** [grokify/go-voicebase-v3#5]
When I `go get github.com/grokify/go-voicebase-v3@master` it fails with 
> ../../go/pkg/mod/github.com/grokify/go-voicebase-v3@v2.3.1-0.20180304064818-74dfa5a927dd+incompatible/media.go:15:16: builder.WriteFile undefined (type multipartutil.MultipartBuilder has no field or method WriteFile)

**Comment by grokify** [comment]
Fixed in release [`v3.0.0`](https://github.com/grokify/go-voicebase-v3/releases/tag/v3.0.0) with the addition of Go modules.
